name: Creative Colours
version: v0.1
main: gamemode.scranner.gamemode
description: 
commands:
    gm:
        description:
        usage: /gm
    gm toggle:
        description:
        usage: /gm toggle
    gm help:
        description:
        usage: /gm help
    gm c:
        description:
        usage: /gm c
    gm s:
        description:
        usage: /gm s
    gm has:
        description:
        usage: /gm has